name: Delete old workflow runs
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  del_runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: Izumiko/delete-workflow-runs@main
        with:
          token: ${{ secrets.AUTH_PAT }}
          repository: |
            Izumiko/lobe-chat
            Izumiko/docker-mihomo
          retain_days: 14
